############################################################################################
### Snakemake configfile for configuring Snakefile inputs
### 3-7-2025


### Set years for data; EIA930 available for 2018 onward for balancing authorities (BAs) and 2019 
  # onward for BA subregions (BASRs).NOAA has less well-defined limits on time periods, but the 
  # further back you go, the more likely missing data will appear.

eia930:
  BA:
    year_start: !!int 2018
    year_end: !!int 2023
  BASR:
    year_start: !!int 2019
    year_end: !!int 2023
noaa:
  year_start: !!int 1990 # Set value to 2019 to test pipeline
  year_end: !!int 2022

# Year to pull county population data for weighting
population_year: !!int 2022

### Location for DB files; original file stored in BlueSky Fileshare
db_directory: "YOUR_PATH_TO/bluesky_prototype/sample/data_pipeline/outputs"

### Number of stations to assign to each county for purposes of county weather series construction
  # Note: Finds N_STATION nearest stations to county centroid. 
n_stations: !!int 10 # Set value to 2 to test pipeline

### Census Key Here to use tidycensus. To get started working with tidycensus, users should load the  
  # package along with the tidyverse package, and set the Census API key. A key can be obtained from 
  # http://api.census.gov/data/key_signup.html.
  # Note: The snakemake rule "county_population" generates the County_Population.csv input file, 
  # but this requires a census key. We've commented out the rule and provided a copy of the CSV in 
  # inputs, in case users are having trouble accessing census keys. 
cenkey: ""

