# RUN CONFIGURATIONS
# This file is used to establish the main model configurations users can edit when running

###################################################################################################
# Universial Inputs

#SETTINGS
# Mode choices=['elec','h2','unified-combo','gs-combo']
# The default mode is only used when --mode argument is not passed by the user when running main.py
default_mode = 'elec'

force_10 = false  # forces 10 iterations in solves that iterate, specify true or false (lowercase)
tol = 0.05  # percent tolerance allowed between iterations, specify a number less than 1
max_iter = 12 # max number of iterations 

sw_temporal = 'bp'

# note: these settings below are csvs for now, future version may be directly specified in toml

# CSV SWITCHES
# These inputs are switches, edit the CSV file, adding a 1 next to the years, regions, etc. 
# in which you would like to run the model for

years = 'src/models/residential/input/sw_year_bp.csv'
regions = 'src/models/residential/input/sw_reg_bp.csv'


###################################################################################################
# Electricity Inputs

#TODO: Move scedes settings here

sw_trade = 1
sw_expansion = 0
sw_agg_years = 0
sw_rm = 0
sw_ramp = 0
sw_reserves = 0
sw_learning = 0
