# RUN CONFIGURATIONS
# This file is used to establish the main model configurations users can edit when running

###################################################################################################
# Universial Inputs

#SETTINGS
# Mode choices=['elec','h2','unified-combo','gs-combo']
# The default mode is only used when --mode argument is not passed by the user when running main.py
default_mode = 'gs-combo'

# Modules to select
electricity = true # specify true or false (lowercase)
hydrogen = false # specify true or false (lowercase)
residential = false # specify true or false (lowercase)

# Choices for combination solves
force_10 = false  # forces 10 iterations in solves that iterate, specify true or false (lowercase)
tol = 0.05  # percent tolerance allowed between iterations, specify a number less than 1
max_iter = 12 # max number of iterations 

sw_temporal = 'd4h1'

# note: these settings below are csvs for now, future version may be directly specified in toml

# CSV SWITCHES
# These inputs are switches, edit the CSV file, adding a 1 next to the years, regions, etc. 
# in which you would like to run the model for

years = "src/integrator/input/sw_year.csv"
regions = "src/integrator/input/sw_reg.csv"


###################################################################################################
# Electricity Inputs

#TODO: Move scedes settings here

sw_trade = 1
sw_expansion = 1
sw_agg_years = 1
sw_rm = 1
sw_ramp = 0
sw_reserves = 1
sw_learning = 1

###################################################################################################
# Residential Inputs

# Select the regions and years you want to graph at the end of the run.
view_regions = [7] # Any subset of available regions to be displayed in a graph
view_years = [2023] # Any subset of available years to be displayed in a graph

### Sensitivity Inputs

sensitivity = true # Set to true to run estimates for changes in Load due to changes in another variable
# Effect Variable options=['price','p_elas','income','i_elas','trendGR']
# The default variable to change is 'price'. This will be altered up and down by the percentage given
# percent_change should be a number between 0 - 100 (eg. 5 would be read as 5% or 0.05)
change_var = "price"
percent_change = 5

#Sensitivity Method: Choose analytical derivative method with false or complex step derivative with true
complex = true

###################################################################################################
# Hydrogen Inputs

h2_data_folder = 'src/models/hydrogen/inputs/single_region'

